---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: default
  labels:
    app: mysvclabel
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp
  type: NodePort
