apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplomentx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: container1
        image: nginx:1.14-alpine-perl           
        ports:
        - containerPort: 80
